# Generated by Django 2.1 on 2019-11-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='books/cover/'),
        ),
    ]
