# Generated by Django 2.1 on 2019-11-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20191114_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='afri_books',
            new_name='african_author',
        ),
    ]
