# Generated by Django 2.1 on 2019-11-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20191114_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Computer Programming', 'Computer Programming'), ('Sci-Fi', 'Sci-Fi'), ('Health', 'Health'), ('Accounting', 'Accounting'), ('Entrepreneurship', 'Entrepreneurship'), ('Law', 'Law'), ('Adventure', 'Adventure'), ('Novel', 'Novel'), ('Health', 'Health'), ('Other', 'Other')], max_length=100, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='Short description about book', max_length=500),
        ),
    ]
