# Generated by Django 2.1 on 2019-11-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_links', '0002_auto_20191107_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefullinks',
            name='logo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
