# Generated by Django 2.1 on 2019-11-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_links', '0003_auto_20191107_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefullinks',
            name='logo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='useful_links/logo/'),
        ),
    ]
