# Generated by Django 2.1 on 2019-11-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_links', '0004_auto_20191107_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefullinks',
            name='logo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='links/logos/'),
        ),
    ]
