# Generated by Django 2.1 on 2019-11-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_links', '0005_auto_20191107_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefullinks',
            name='category',
            field=models.CharField(help_text='Genre can be in Computer Programming,\t\t\t\t\t\t\t\tBusiness, Law, Medicine, Engineering, Accounting etc. Just one that fit the description of the url!', max_length=100, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='usefullinks',
            name='description',
            field=models.TextField(blank=True, help_text='Short description about website/course/link', max_length=500),
        ),
        migrations.AlterField(
            model_name='usefullinks',
            name='url_link',
            field=models.URLField(help_text='Please indicate the correct url!'),
        ),
    ]
